### ISSUE TITLE
Branding/Naming

### ISSUE THREAD

**Issue by MattBlaK** [HammondeUtility/MARS-One#2]
Pretty stuff: Rename it to MARS cos it’s a better acronym (Medical Appraisal & Revalidation System (Service/Support). 

In demo files anything star wars has been my go to sample names (seems to work on Ray).

**Comment by mhammonde** [comment]
Are there any further suggestions on this item @MattBlaK? Something like eMARS or similar?

**Comment by mhammonde** [comment]
Agreed on "MARS One"
